version: '3.4'

services:
  qs:
    image: qs
    build:
      context: server/node_modules/qs
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
