FROM node:lts
RUN apt-get update
RUN apt-get install
RUN apt install -y ffmpeg
RUN apt install sudo
RUN sudo apt update
RUN sudo apt install -y cifs-utils
RUN mkdir -p home/henry/codentv2a
RUN chmod 755 home/henry/codentv2a
RUN mkdir -p home/henry/codentv1c
RUN chmod 755 home/henry/codentv1c